### PR TITLE
Update donation link

### LINKED ISSUE #411: Track transdimension.uk donations separately
Was acceptance for #272 that maybe got overlooked.

Also might be a good idea to link to the GI donations page rather than direct to Just giving at this point.

### PR DESCRIPTION
**Pull request by kimadactyl**
Closes #411

Before merging need to:

* [x] Set up Stripe account properly
* [x] Link it to Donorbox
* [x] Customise the donate page a little more

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkZmU4YWU3Y2M1YTc4NTQyZTVjYzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.NecKAGQfQFUrpNftblM-Qa_o-92dbqC_dZyVX_VWSuM">Huly&reg;: <b>TD-457</b></a></sub>

### CODE REVIEW

**Comment by kimadactyl** [comment]
ok i think this is Good Enough now but could have more done to make the donate page nicer as always - what do you think?

**Review by katjam — APPROVED** [review]
This looks good to me with tiny concern.

I'm happy for it to be merged as long as there is agreement from GI for removing the link to their donation page & we are happy on the level of transparency on what the donation will be used for. Not my call but feels a bit of a grey area at the moment. 

We could make it more clear who the money is going to. Is it PHT as the comment says, GFSC as the donation account owner a "trustee body" for The Trans Dimension project specifically as the link & information suggests? Is the Trans Dimension a collaboration with GI as the site branding suggests (including the copyright) or is it only a PHT project now? I feel like this was more clear before we added Manchester as in GFSC was commissioned to create Trans Dimension for GI and it was "powered by" PHT software PlaceCal.

It may be that none of this matters but it feels muddy and could maybe do with a statement that is agreed by all 3 parties in the footer and some kind of formal breakdown of proportions of funding shared out to each of those 3.

**Comment by kimadactyl** [comment]
OK, I’ll get all this in an email next week and agree all this with GI. I think at this point I’m less worried where it ends up and more just having the ability to track the donations for it in a separate pot. Our bottom line is that the project is hugely over budget and we need to start recouping somehow.

**Comment by katjam** [comment]
Totally understand your position. Trying to make sure there is some statement of agreement to avoid confusion/stress down the line.

**Comment by katjam** [comment]
Merging to staging so we can preview all of these together

**Pull request merged**
