### PR TITLE
feat: Filter by date and region on index, events and partner pages

### LINKED ISSUE #408: Add in regional selector
## Description

Add in regional selection options.

## Acceptance Criteria

- [ ] There is a regional selector on the homepage
- [ ] There is a regional selector on events page
- [ ] There is a regional selector on partners page

## Plan

- [x] Import data from multiple partnership tags
- [x] Add partnership ID to event data
- [x] Add partnership ID to partner data
- [x] Check if News is segmented by partnership tag currently & adjust accordingly (#456 )
- [x] Add controls to site index page for filtering by partnership tag
- [x] #464
- [x] Add controls to events index page for filtering by partnership tag
- [x] Order mixed region lists of events by datetime - so they are intermingled

## Designs and detail can be found at the below links:

**Desktop export**
https://xd.adobe.com/view/17da1e7c-3265-4fe7-b5c1-27f8988821cb-4289/
Hover states are provided and various options for what happens when we have more than two regions are provided

**Mobile export**
https://xd.adobe.com/view/9bd8899a-3135-4e63-a651-5e4385661da6-ce8b/
There are two design options for the regions in the visuals, honor preferred it being stacked vertically than two columns, and inquired about introducing a dropdown if we had more regions. No further feedback was provided. Mark has no preference as to which design is implemented, whatever works easiest and meets best dev practice ideally?

### PR DESCRIPTION
**Pull request by katjam**
Fixes #408

## Description

- Adds regional selector to index page
- Moves event lists out of model & instead calculate from filters
- Correct featured events on index to show draw from all future, not just today

TODO: Would like to add tests for event listings

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlNTllNGU3Y2M1YTc4NTQyOTk0OWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.6sYBEmyV2h63ye48FPotHgVNikrmCyXvBN_xRYIol54">Huly&reg;: <b>TD-453</b></a></sub>

### CODE REVIEW

**Comment by kimadactyl** [comment]
Not sure if you want me to review yet but just had a look and looking nice but:

- Events for manchester not showing up at all - is this just becuase it's not merged into main?
- Something odd's happened to the news!

**Comment by katjam** [comment]
The news is missing images because for some reason they don't exit on staging. We did at some point have placeholder images but I'm not sure if I ported that across. I'll check.

There were events in Manchester for some dates. This may be because is using staging data.  I'll check that too. Maybe we should temporarily point preview branches at production PlaceCal to verify before merging? I'll make a staging branch again now so we can preview all of these small changes together before going live.

**Comment by kimadactyl** [comment]
> There were events in Manchester for some dates. This may be because is using staging data. I'll check that too. Maybe we should temporarily point preview branches at production PlaceCal to verify before merging?

Ah right that makes sense! Yes let's build vs prod, right now there's zero events on staging coming through :)

> The news is missing images because for some reason they don't exit on staging.

Ah - we only have db sync from prod->staging not storage sync. Prob why!

**Comment by katjam** [comment]
Merging to staging for preview before we send live this week.

**Pull request merged**
